name: McXyhjGame
version: ${project.version}
main: mcxyhj.cn.knkiss.McXyhjGame
api-version: 1.16
authors: [ knkiss, Dnkiss ]
description: Game plugin for mcxyhj
website: mcxyhj.cn

commands:
  game:
    description: 关于游戏的指令

permissions:
  mcxyhj.game.admin:
    description: commands about plugin
    children:
      mcxyhj.game.debug: true
